# Generated by Django 5.1.1 on 2024-09-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("telefone", models.CharField(max_length=15)),
                ("endereco", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField()),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("endereco", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Manhã", "Manhã"),
                            ("Tarde", "Tarde"),
                            ("Noite", "Noite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="central.cuidador",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="central.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pressao_sistolica", models.IntegerField(blank=True, null=True)),
                ("pressao_diastolica", models.IntegerField(blank=True, null=True)),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("saturacao_o2", models.IntegerField(blank=True, null=True)),
                ("glicemia", models.IntegerField(blank=True, null=True)),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="central.cuidador",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="central.paciente",
                    ),
                ),
            ],
        ),
    ]
