# Generated by Django 5.1.1 on 2024-09-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("central", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuidador",
            name="endereco",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="endereco",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuidador",
                    models.CharField(
                        choices=[
                            ("CUIDADOR_1", "Cuidador 1"),
                            ("CUIDADOR_2", "Cuidador 2"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "turno_duracao",
                    models.IntegerField(
                        choices=[(24, "24 horas"), (48, "48 horas"), (72, "72 horas")]
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="central.paciente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Escala",
        ),
    ]
