# Generated by Django 5.1.1 on 2024-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("central", "0004_cuidador_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="obs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
